"""auto bootstrap

Revision ID: 60adf486f13c
Revises: 
Create Date: 2025-05-13 15:18:41.029538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60adf486f13c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('v_token', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('v_token')
        batch_op.drop_column('verified')

    # ### end Alembic commands ###
